---
title: "R Notebook"
output: html_notebook
---



```{r}
## AUTATI A CARICARE IL DATABASE


```



```{r}

#QUERY MYSQL

#1 Fedeltà clienti , quanti abbonamenti sono stati rinnovati
Query1=tibble(sqlQuery("SELECT (COUNT(Tessera)-1) AS ABBONAMENTI_RINNOVATI
                        FROM Scaduto FULL JOIN Valido ON Scaduto.Tessera = Valido.Tessera 
                        GROUP BY Tessera"))

#2 Stampa numero di corse per anno
Query2=tibble(sqlQuery("SELECT EXTRACT(YEAR from Dataora) AS Anno, COUNT(*)
                        FROM CORSA
                        GROUP By Anno"))

#3 Luogo di residenza degli abbonati
Query3=tibble(sqlQuery("SELECT LuogoDiResidenza 
                        FROM Cliente
                        GROUP BY LuogoDiResidenza"))
#4 Numeri di abbonati che usufruiscono del servizio per anno, GRAFICO PUNTO LINEA
Query4=tibble(sqlQuery("SELECT Count(Cliente),EXTRACT(YEAR from Dataora) AS YEAR
                       FROM HaUsufruito
                       GROUP BY YEAR"))

#5 Distribuzione di età degli abbonati, GRAFICO A TORTA
Query5=tibble(sqlQuery("SELECT EXTRACT(YEAR from DataDiNascita)AS YEAR
                       FROM CLIENTE
                       GRUOP BY YEAR "))
#6 Autisti che hanno fatto più corse 
Query6=tibble(sqlQuery("SELECT AUTISTA,COUNT(AUTISTA) AS Numero_Corse
                       FROM HaEseguito
                       GRUOP BY AUTISTA"))

```
.
