version: '3.1'

services:
  postgres-db:
    build: .
    volumes:
      - './sql/:/docker-entrypoint-initdb.d/'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432 
