---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(DBI)
library(RPostgres)
```


```{r}
host_db <- "localhost"
db_port <- "5432"
db <- "postgres"
db_user <- "postgres"
db_password <- "postgres"
db_schema <- "SistemaTrasportoUrbano"


dpi = 500
```

```{r}
con <- dbConnect(
            Postgres(),
            dbname = db,
            host = host_db,
            port = db_port,
            user = db_user,
            password = db_password,
            options = paste("-c search_path=", db_schema, sep = "")
    )
```


```{r}
query <- function(con, query) {
    res <- dbSendQuery(con, query)
    result <- tibble(dbFetch(res))
    dbClearResult(res)

    result
}
```


```{r}
# ----------- #
# - Queries - #
# ----------- #

# 1 Fedeltà clienti, quanti abbonamenti sono stati rinnovati
query_1 <- query(con, "SELECT Card, COUNT(*) AS num
                       FROM (SELECT COUNT(*) AS Card
                       FROM Abbonamento
                       GROUP BY Tessera) AS TMP
                       GROUP BY Card")

# 2 Stampa numero di corse per anno
query_2 <- query(con, "SELECT EXTRACT(YEAR from DataOra) AS Anno,
                              COUNT(*) AS num
                       FROM Corsa INNER JOIN HaEseguito
                            ON EseguitoId = Id
                       GROUP By Anno")

# 3 Luogo di residenza degli abbonati
query_3 <- query(con, "SELECT LuogoResidenza
                       FROM Cliente")

# 4 Numeri di abbonati che usufruiscono del servizio per anno
# GRAFICO PUNTO LINEA
query_4 <- query(con, "SELECT Count(Cliente) AS NUMERO,
                              EXTRACT(YEAR from Dataora) AS YEAR
                       FROM HaUsufruito INNER JOIN HaEseguito
                            ON EseguitoId = Id
                       GROUP BY YEAR")

# 5 Distribuzione di età degli abbonati, GRAFICO A TORTA
query_5 <- query(con, "SELECT COUNT(*) AS num,
                              EXTRACT(YEAR from DataNascita) AS YEAR
                      FROM Cliente
                      GROUP BY YEAR")

# 6 Autisti che hanno fatto più corse
query_6 <- query(con, "SELECT Autista,COUNT(Autista) AS NUMERO_CORSE
                      FROM HaEseguito
                      GROUP BY Autista")
```


```{r}
print(query_1)
print(query_2)
print(query_3)
print(query_4)
print(query_5)
print(query_6)
```


```{r}
tmp <- query_1 %>%
    mutate_all(as.numeric) %>%
    transform(card = as.character(card)) %>%
    ggplot(aes(x = card, y = num, fill = -num)) +
    geom_bar(stat = "identity", colour = "black") +
    scale_y_continuous(limits = c(0, 6000)) +
    theme(legend.position = "none") +
    labs(
         x = "Numero di abbonamenti rinnovati",
         y = "Occorrenze",
         title = "Numero di volte in cui un abbonamento viene rinnovato"
    ) +
    scale_fill_continuous(low = "#511845", high = "#ff5733")

tmp
ggsave("output/query_1.png", tmp, dpi = dpi)
```


```{r}
tmp <- query_2 %>%
    mutate_all(as.numeric) %>%
    transform(anno = as.character(anno)) %>%
    arrange(-num) %>%
    head(10) %>%
    ggplot(aes(x = reorder(anno, -num), y = num, fill = -num)) +
    geom_bar(stat = "identity", colour = "black") +
    theme(legend.position = "none") +
    scale_y_continuous(limits = c(0, 3400)) +
    labs(
         x = "Anno",
         y = "Numero corse",
         title = "Numero di corse per anno (top 10)"
    ) +
    scale_fill_continuous(low = "#e18400", high = "#ffff00")

tmp
ggsave("output/query_2.png", tmp, dpi = dpi)
```


```{r}
tmp <- query_3 %>%
    mutate(
           provincia = str_match(luogoresidenza, ".*\\(([A-Z]{2})\\).*$")[, 2]
    ) %>%
    select(provincia) %>%
    count(provincia) %>%
    arrange(-n) %>%
    head(10) %>%
    ggplot(aes(x = reorder(provincia, -n), y = n, fill = -n)) +
    geom_bar(stat = "identity", colour = "black") +
    theme(legend.position = "none") +
    labs(
         x = "Provincia",
         y = "Occorrenze",
         title = "Provincie di appartenenza dei clienti (top 10)"
    ) +
    scale_fill_continuous(low = "#00909e", high = "#c8faff")

tmp
ggsave("output/query_3.png", tmp, dpi = dpi)
```


```{r}
tmp <- query_4 %>%
    mutate_all(as.numeric) %>%
    transform(year = as.character(year)) %>%
    ggplot(aes(x = year, y = numero, group = 1)) +
    geom_line(color = "#f8766d") +
    geom_point() +
    labs(
         x = "Anno",
         y = "Corse",
         title = "Numero di corse per ogni anno"
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5))


tmp
ggsave("output/query_4.png", tmp, dpi = dpi)
```


```{r}
tmp <- query_5 %>%
    mutate_all(as.numeric) %>%
    mutate(year = 2021 - year) %>%
    filter(year < 100) %>%
    transform(year = as.character(year)) %>%
    arrange(-num) %>%
    head(8) %>%
    ggplot(aes(x = "", y = num, fill = year)) +
    geom_bar(stat = "identity", width = 1, color = "white") +
    coord_polar("y", start = 0) +
    theme_void() +
    labs(title = "Età dei clienti (top 8)", fill = "Anno") +
    geom_text(aes(label = scales::percent(num / sum(num))),
            position = position_stack(vjust = 0.5)) +
    scale_fill_brewer(palette = "Dark2")


tmp
ggsave("output/query_5.png", tmp, dpi = dpi)
```


```{r}
tmp <- query_6 %>%
   mutate(numero_corse = as.numeric(numero_corse)) %>%
   arrange(-numero_corse) %>%
   head(10) %>%
   ggplot(aes(x = reorder(autista, -numero_corse),
              y = numero_corse, fill = -numero_corse)) +
   geom_bar(stat = "identity", colour = "black") +
   theme(legend.position = "none") +
   labs(
        x = "Autista",
        y = "Numero corse",
        title = "Numero di corse per autista (top 10)"
   ) +
   scale_fill_continuous(low = "#323232", high = "#0077b6") +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5))

tmp
ggsave("output/query_6.png", tmp, dpi = dpi)
```


```{r}
get_times <- function(con, query) {
    repetitions <- 30
    times <- tibble(plan_time = numeric(), exec_time = numeric())
    for (i in seq(1, repetitions)) {
        res <- query(con, query)

        res <- res %>% tail(2)
        times <- times %>%
            rbind(c(as.numeric(str_match(res[1, ], "Planning Time: (.*) ms")[, 2]),
                    as.numeric(str_match(res[2, ], "Execution Time: (.*) ms")[, 2])))
    }
    colnames(times) <- c("plan_time", "exec_time")
    times
}

times1 <- get_times(con, "EXPLAIN ANALYZE
                          SELECT COUNT(*)
                          FROM Valido")

times2 <- get_times(con, "EXPLAIN ANALYZE
                          SELECT COUNT(*) 
                          FROM Abbonamento 
                          WHERE 
                            (tipoabbonamento = 'trimestrale' AND datainizio + INTERVAL '84d' >= NOW()) 
                            OR (tipoabbonamento = 'mensile' AND datainizio + INTERVAL '28d' >= NOW()) 
                            OR (tipoabbonamento = 'annuale' AND datainizio + INTERVAL '365d' >= NOW())")
final_plan <- union(
    times1 %>%
    summarise(mean = mean(plan_time),
              sd = sd(plan_time)) %>%
    mutate(category = "Con Valido"),
    times2 %>%
    summarise(mean = mean(plan_time),
              sd = sd(plan_time)) %>%
    mutate(category = "Senza Valido")
)

final_exec <- union(
    times1 %>%
    summarise(mean = mean(exec_time),
              sd = sd(exec_time)) %>%
    mutate(category = "Con Valido"),
    times2 %>%
    summarise(mean = mean(exec_time),
              sd = sd(exec_time)) %>%
    mutate(category = "Senza Valido")
)

tmp <- final_plan %>%
    ggplot(aes(x = category, fill = category)) +
    geom_boxplot(
                 aes(lower = mean - sd,
                     upper = mean + sd,
                     middle = mean,
                     ymin = mean - 3 * sd,
                     ymax = mean + 3 * sd),
                 stat = "identity") +
    theme(legend.position = "none") +
    labs(x = "",
         y = "Tempo (ms)",
         title = "Tempo di pianificazione")

ggsave("output/valido_plan.png", tmp, dpi = dpi)

tmp <- final_exec %>%
    ggplot(aes(x = category, fill = category)) +
    geom_boxplot(
                 aes(lower = mean - sd,
                     upper = mean + sd,
                     middle = mean,
                     ymin = mean - 3 * sd,
                     ymax = mean + 3 * sd),
                 stat = "identity") +
    theme(legend.position = "none") +
    labs(x = "",
         y = "Tempo (ms)",
         title = "Tempo di esecuzione")

ggsave("output/valido_exec.png", tmp, dpi = dpi)
```


```{r}
query(con, "SET enable_seqscan = OFF")
# Still doesn't uses the given index!
query(con, "EXPLAIN ANALYZE
            SELECT COUNT(*)
            FROM Corsa INNER JOIN HaEseguito 
                 ON EseguitoId = Id 
            WHERE date_trunc('month', DataOra)
                    = date_trunc('month', NOW());")

```


```{r}
# Disconnect from the database
dbDisconnect(con)
```
